import random
from datetime import datetime

from scripts.templates.generators.fields.generate_fake_credit_card_number import generate_random_credit_card_number


def get_random_bank(**kwargs):
    banks = [
        "JPMorgan Chase Bank",
        "Bank of America",
        "Wells Fargo Bank",
        "Citibank",
        "U.S. Bank",
        "PNC Bank",
        "Truist Bank",
        "TD Bank",
        "Capital One",
        "Goldman Sachs Bank USA",
        "HSBC Bank USA",
        "American Express National Bank",
        "Fifth Third Bank",
        "Regions Bank",
        "Citizens Bank",
        "BMO Harris Bank",
        "KeyBank",
        "Ally Bank",
        "Huntington National Bank",
        "Synchrony Bank",
        "Charles Schwab Bank",
        "M&T Bank",
        "BBVA USA",
        "Discover Bank",
        "First Republic Bank",
        "Silicon Valley Bank",
        "Signature Bank",
        "Comerica Bank",
        "First Citizens Bank",
        "MUFG Union Bank",
        "First Horizon Bank",
        "Associated Bank",
        "Western Alliance Bank",
        "Valley National Bank",
        "Zions Bank",
        "Popular Bank",
        "New York Community Bank",
        "FNB Corporation",
        "Raymond James Bank",
        "City National Bank",
        "Fulton Bank",
        "Texas Capital Bank",
        "East West Bank",
        "Wintrust Bank",
        "UMB Bank",
        "Webster Bank",
        "Old National Bank",
        "South State Bank",
        "Prosperity Bank",
        "Synovus Bank",
        "Bank OZK",
        "United Bank",
        "Cadence Bank",
        "Bank of the West",
        "Columbia Bank",
        "Seacoast National Bank",
        "Pacific Western Bank",
        "Hanmi Bank",
        "Banner Bank",
        "Trustmark National Bank",
        "Pinnacle Bank",
        "BankUnited",
        "Atlantic Union Bank",
        "ServisFirst Bank",
        "Old Second National Bank",
        "NBT Bank",
        "Great Western Bank",
        "Simmons Bank",
        "HomeStreet Bank",
        "First Interstate Bank",
        "Washington Federal",
        "Cadence Bank",
        "Independent Bank",
        "S&T Bank",
        "EagleBank",
        "MidFirst Bank",
        "Civista Bank",
        "Stock Yards Bank & Trust",
        "Glacier Bank",
        "Ameris Bank",
        "WSFS Bank",
        "NBT Bank",
        "MetaBank",
        "Sterling National Bank",
        "Peoples Bank",
        "First Bank",
        "Citizens Business Bank",
        "Lakeland Bank",
        "First National Bank of Omaha",
        "United Community Bank",
        "Heartland Financial USA",
        "Community Bank System",
        "UMB Financial Corporation",
        "Sandy Spring Bank",
        "First Merchants Bank",
        "Southwest Bank",
        "International Bank of Commerce",
        "Coastal Community Bank",
        "Central Bank",
        "Farmers and Merchants Bank"
    ]

    return random.choice(banks)


def get_random_card_name(**kwargs):
    card_names = [
        "CitibankPlus",
        "BankAmericard",
        "Infinite Points",
        "TruistLine",
        "Chase Freedom",
        "Wells Rewards",
        "Amex Gold",
        "Capital One Venture",
        "Discover It",
        "PNC Cash Rewards",
        "U.S. Bank FlexPerks",
        "Bank of America Platinum",
        "TD First Class",
        "HSBC Elite",
        "Fifth Third Preferred",
        "Regions Prestige",
        "Citizens Access",
        "Ally Cashback",
        "KeyBank Preferred",
        "Synchrony Premier",
        "Schwab Investor",
        "M&T Rewards",
        "BBVA ClearPoints",
        "First Republic Eagle",
        "Silicon Valley Advantage",
        "Signature Select",
        "Comerica Power",
        "First Citizens Prime",
        "MUFG Union Privilege",
        "First Horizon Elite",
        "Associated Platinum",
        "Western Alliance Premier",
        "Valley National Rewards",
        "Zions Prestige",
        "Popular Platinum",
        "New York Community Premier",
        "FNB Rewards",
        "Raymond James Signature",
        "City National Elite",
        "Fulton Preferred",
        "Texas Capital Advantage",
        "East West Elite",
        "Wintrust Rewards",
        "UMB Platinum",
        "Webster Premier",
        "Old National Prestige",
        "South State Rewards",
        "Prosperity Prime",
        "Synovus Signature",
        "Bank OZK Elite",
        "United Rewards",
        "Cadence Premier",
        "Bank of the West Platinum",
        "Columbia Prime",
        "Seacoast National Preferred",
        "Pacific Western Premier",
        "Hanmi Elite",
        "Banner Rewards",
        "Trustmark Prestige",
        "Pinnacle Signature",
        "BankUnited Platinum",
        "Atlantic Union Elite",
        "ServisFirst Rewards",
        "Old Second Premier",
        "NBT Prime",
        "Great Western Prestige",
        "Simmons Elite",
        "HomeStreet Rewards",
        "First Interstate Prime",
        "Washington Federal Premier",
        "Independent Advantage",
        "S&T Elite",
        "EagleBank Prestige",
        "MidFirst Rewards",
        "Civista Premier",
        "Stock Yards Prime",
        "Glacier Signature",
        "Ameris Elite",
        "WSFS Rewards",
        "MetaBank Prestige",
        "Sterling National Premier",
        "Peoples Advantage",
        "First Prime",
        "Citizens Business Rewards",
        "Lakeland Prestige",
        "First National Bank of Omaha Premier",
        "United Community Prime",
        "Heartland Financial Elite",
        "Community Bank System Prestige",
        "UMB Financial Advantage",
        "Sandy Spring Signature",
        "First Merchants Rewards",
        "Southwest Premier",
        "International Bank of Commerce Prime",
        "Coastal Community Elite",
        "Central Bank Rewards",
        "Farmers and Merchants Premier"
    ]

    return random.choice(card_names)


def get_random_card_phrase(**kwargs):
    card_phrases = [
        "CASH REWARDS",
        "5% CASH BACK",
        "FREE MILES",
        "DISCOUNTS",
        "TRAVEL POINTS",
        "BONUS POINTS",
        "NO ANNUAL FEE",
        "ZERO INTEREST",
        "DOUBLE REWARDS",
        "FUEL SAVINGS",
        "SHOPPING DISCOUNTS",
        "DINING REWARDS",
        "HOTEL POINTS",
        "AIRLINE MILES",
        "GROCERY REWARDS",
        "ENTERTAINMENT POINTS",
        "CASH BONUSES",
        "INTRO APR",
        "LOW INTEREST",
        "BALANCE TRANSFER",
        "NO FOREIGN FEES",
        "VIP ACCESS",
        "PREMIUM SUPPORT",
        "EXCLUSIVE OFFERS",
        "MEMBER PERKS",
        "SHOPPING CREDITS",
        "TRAVEL INSURANCE",
        "EXTENDED WARRANTY",
        "PURCHASE PROTECTION",
        "FRAUD ALERTS",
        "MOBILE PAY",
        "RENTAL CAR INSURANCE",
        "PRICE PROTECTION",
        "ACCESS TO LOUNGES",
        "CONCIERGE SERVICE",
        "EARLY ACCESS",
        "SIGN-UP BONUS",
        "REFERRAL BONUS",
        "REWARD MULTIPLIER",
        "BONUS CATEGORY",
        "REDEEM FOR CASH",
        "GIFT CARDS",
        "STATEMENT CREDITS",
        "CASH BACK MATCH",
        "UNLIMITED REWARDS",
        "POINTS MULTIPLIER",
        "ONLINE ACCOUNT",
        "CARD MEMBER SAVINGS",
        "SPECIAL FINANCING",
        "FLEXIBLE PAYMENTS",
        "CUSTOMER SUPPORT",
        "POINTS REDEMPTION",
        "CARDHOLDER BENEFITS",
        "ADDITIONAL CARDS",
        "FRAUD PROTECTION",
        "EMERGENCY ASSISTANCE",
        "DIGITAL WALLET",
        "EXPEDITED SHIPPING",
        "EARN REWARDS",
        "TRAVEL BENEFITS",
        "CASH BACK OFFERS",
        "SHOPPING REWARDS",
        "LOYALTY POINTS",
        "PREFERRED REWARDS",
        "REDEEM POINTS",
        "ANNUAL SAVINGS",
        "TRAVEL CREDITS",
        "LOUNGE ACCESS",
        "HOTEL DISCOUNTS",
        "CAR RENTAL DISCOUNTS",
        "AIR MILEAGE",
        "FREE CHECKED BAGS",
        "CREDIT MONITORING",
        "IDENTITY THEFT PROTECTION",
        "TSA PRE-CHECK",
        "GLOBAL ENTRY",
        "UNLIMITED POINTS",
        "EARN CASH",
        "TRAVEL PERKS",
        "FLEXIBLE REWARDS",
        "REWARD POINTS",
        "SIGN-UP REWARDS",
        "ANNUAL FEE WAIVED",
        "PREFERRED ACCESS",
        "SPECIAL OFFERS",
        "LOW APR",
        "CASH BACK BONUS",
        "ADDITIONAL REWARDS",
        "REWARD PROGRAM",
        "LOYALTY REWARDS",
        "SHOPPING BONUSES",
        "POINTS FOR PURCHASES",
        "TRAVEL EXPENSES",
        "AIRLINE TICKETS",
        "FREE NIGHTS",
        "LUXURY REWARDS",
        "SPECIAL DISCOUNTS",
        "EARN MORE",
        "REWARD LEVEL",
        "ADDITIONAL BENEFITS"
    ]

    return random.choice(card_phrases)


def generate_credit_card(**kwargs):
    return generate_random_credit_card_number()[1]


def generate_payment_network(**kwargs):
    return generate_random_credit_card_number()[0]


def get_random_flavor(**kwargs):
    card_types = [
        "Signature", "Affinity", "Elite", "Platinum", "Gold", "Rewards", "Cashback",
        "Travel", "Business", "Corporate", "Prepaid", "Debit", "Student", "Premier",
        "Select", "Preferred", "Classic", "Ultimate", "Luxury", "Exclusive",
        "Infinite", "Value", "Privilege", "Secure", "Diamond", "Infinite",
        "Titanium", "Prestige", "Freedom", "Emerald", "Prime", "Advantage",
        "Optimum", "Express", "Liberty", "Vantage", "Supreme", "Victory",
        "Momentum", "Radiant", "Legend", "Ascend", "Quest", "Vibrant", "Zenith",
        "Eclipse", "Crescent", "Pinnacle", "Odyssey", "Glory", "Genesis",
        "Virtue", "Serenity", "Aura", "Harmony", "Bliss", "Euphoria", "Gleam",
        "Essence", "Pulse", "Beacon", "Compass", "Journey", "Voyage", "Voyager",
        "Venture", "Oasis", "Meridian", "Horizon", "Vista", "Expedition",
        "Pioneer", "Envision", "Summit", "Elevate", "Strive", "Ambition",
        "Clarity", "Zen", "Fusion", "Velocity", "Pursuit", "Endeavor",
        "Aspire", "Finesse", "Charm", "Blaze", "Spark", "Flair", "Glide",
        "Radiance", "Prestige", "Luster", "Mystique", "Edge", "Impact"
    ]

    return random.choice(card_types)


def generate_random_valid_thru(**kwargs):
    current_year = datetime.now().year
    month = random.randint(1, 12)
    year = random.randint(current_year, current_year + 5)  # Valid for up to 5 years from now
    return f"{month:02d}/{str(year)[-2:]}"


